name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: lint the code
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2
      
      - name: lint
        run: make lint
  
  test:
    name: execute the test suite
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2

      - name: execute tests
        run: make test

  build:
    name: Create binary executable
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make build
    
